import webapp.models as model

# DiningCluster
cluster_1 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.34621, longitude=103.68866)
cluster_2 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.34435, longitude=103.67847)
cluster_3 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.35049, longitude=103.68795)
cluster_4 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.34520, longitude=103.67820)
cluster_5 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.35225, longitude=103.68147)
cluster_6 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.35051, longitude=103.68138)
cluster_7 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.34842, longitude=103.68543)
cluster_8 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.35476, longitude=103.68468)
cluster_9 = model.DiningCluster(name="North Spine1", postal_code=123456, latitude=1.34523, longitude=103.68538)
cluster_10 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.35430, longitude=103.68645)
cluster_11 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.35397, longitude=103.68801)
cluster_12 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.34183, longitude=103.68192)
cluster_13 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.34251, longitude=103.68025)
cluster_14 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.34713, longitude=103.68003)
cluster_15 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.34320, longitude=103.68266)
cluster_16 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.35247, longitude=103.68164)
cluster_17 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.34345, longitude=103.68238)
cluster_18 = model.DiningCluster(name="North Spine2", postal_code=123456, latitude=1.34367, longitude=103.68314)
cluster_1.save()
cluster_2.save()
cluster_3.save()
cluster_4.save()
cluster_5.save()
cluster_6.save()
cluster_7.save()
cluster_8.save()
cluster_9.save()
cluster_10.save()
cluster_11.save()
cluster_12.save()
cluster_13.save()
cluster_14.save()
cluster_15.save()
cluster_16.save()
cluster_17.save()
cluster_18.save()

# DiningSubArea
subarea_1 = model.DiningSubArea(loc='North Spine Food Court', cluster=cluster_1)
subarea_2 = model.DiningSubArea(loc='North Spine Plaza', cluster=cluster_10)
subarea_1.save()
subarea_2.save()

# DiningArea
diningarea_1 = model.DiningArea(name='Hand-made Noodles', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=1838, dining_type='Food Court', sub_loc=subarea_1, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_2 = model.DiningArea(name='Chicken Rice', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=1838, dining_type='Food Court', sub_loc=subarea_1, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_3 = model.DiningArea(name='Mini Wok', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=1838, dining_type='Food Court', sub_loc=subarea_1, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_4 = model.DiningArea(name='Soup Delight', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=1838, dining_type='Food Court', sub_loc=subarea_1, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_5 = model.DiningArea(name='Western Food', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=1838, dining_type='Food Court', sub_loc=subarea_1, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_6 = model.DiningArea(name='Mr Bean', addr="North Spine Plaza 50 Nanyang Avenues " + \
                                "NS3-01-16 Singapore 639798", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=0, dining_type='Restaurant', sub_loc=subarea_2, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_7 = model.DiningArea(name="Paik's Bibim", addr="North Spine Plaza 50 Nanyang Avenues " + \
                                "NS3-01-16 Singapore 639798", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=40, dining_type='Restaurant', sub_loc=subarea_2, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_8 = model.DiningArea(name='Peach Garden Chinese Restaurant', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=180, dining_type='Restaurant', sub_loc=subarea_2, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_9 = model.DiningArea(name='PEN & INC', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=144, dining_type='Restaurant', sub_loc=subarea_2, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_10 = model.DiningArea(name='​Pizza Hut Express', addr="North Spine Plaza 76 Nanyang " + \
                                "Drive NS2.1-02-03/01A Singapore 637331", phone_no='6465 8588', \
                                operating_hour='Mon to Fri: 7am to 9pm Sat: 7am to 3pm Sun & PH: Closed', \
                                capacity=162, dining_type='Restaurant', sub_loc=subarea_2, \
                                imgurl="/static/webapp/assets/co-op.jpg")
diningarea_1.save()
diningarea_2.save()
diningarea_3.save()
diningarea_4.save()
diningarea_5.save()
diningarea_6.save()
diningarea_7.save()
diningarea_8.save()
diningarea_9.save()
diningarea_10.save()


# Assets
asset_1 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_1)
asset_2 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_1)
asset_3 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_2)
asset_4 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_2)
asset_5 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_3)
asset_6 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_3)
asset_7 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_4)
asset_8 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_4)
asset_9 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_5)
asset_10 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_5)
asset_11 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_6)
asset_12 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_6)
asset_13 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_7)
asset_14 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_7)
asset_15 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_8)
asset_16 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_8)
asset_17 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_9)
asset_18 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_9)
asset_19 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_10)
asset_20 = model.DiningAreaAssets(url="/static/webapp/assets/co-op.jpg", dining_area=diningarea_10)
asset_1.save()
asset_2.save()
asset_3.save()
asset_4.save()
asset_5.save()
asset_6.save()
asset_7.save()
asset_8.save()
asset_9.save()
asset_10.save()
asset_11.save()
asset_12.save()
asset_13.save()
asset_14.save()
asset_15.save()
asset_16.save()
asset_17.save()
asset_18.save()
asset_19.save()
asset_20.save()

# Menu
menu_1 = model.Menu(name='San Mian Moe Hoon Kway', price=3.30, dining_area=diningarea_1)
menu_2 = model.Menu(name='Sichuan Veg Ban Mian', price=3.30, dining_area=diningarea_1)
menu_3 = model.Menu(name='Sliced Fish Ban Mian', price=3.50, dining_area=diningarea_1)
menu_4 = model.Menu(name='Steamed Chicken Rice', price=2.80, dining_area=diningarea_2)
menu_5 = model.Menu(name='Roasted Chicken Rice', price=2.80, dining_area=diningarea_2)
menu_6 = model.Menu(name='Lemon Chicken Rice', price=2.80, dining_area=diningarea_2)
menu_7 = model.Menu(name='Sambal Chicken Fried Rice', price=3.50, dining_area=diningarea_3)
menu_8 = model.Menu(name='Salted Fish Fried Rice', price=3.50, dining_area=diningarea_3)
menu_9 = model.Menu(name='Fried Rice with Prawn', price=3.50, dining_area=diningarea_3)
menu_10 = model.Menu(name='BBQ Chicken', price=3.80, dining_area=diningarea_4)
menu_11 = model.Menu(name='Fish Fillet', price=3.80, dining_area=diningarea_4)
menu_12 = model.Menu(name='Combo Meal (Chicken + Fish)', price=5.00, dining_area=diningarea_4)
menu_13 = model.Menu(name='Mixed Pork Soup', price=3.80, dining_area=diningarea_5)
menu_14 = model.Menu(name="Pig's Liver Soup'", price=3.80, dining_area=diningarea_5)
menu_15 = model.Menu(name='Lean Meat Soup', price=3.80, dining_area=diningarea_5)
menu_16 = model.Menu(name='San Mian Moe Hoon Kway', price=3.30, dining_area=diningarea_6)
menu_17 = model.Menu(name='Sichuan Veg Ban Mian', price=3.30, dining_area=diningarea_6)
menu_18 = model.Menu(name='Sliced Fish Ban Mian', price=3.50, dining_area=diningarea_6)
menu_19 = model.Menu(name='Steamed Chicken Rice', price=2.80, dining_area=diningarea_7)
menu_20 = model.Menu(name='Roasted Chicken Rice', price=2.80, dining_area=diningarea_7)
menu_21 = model.Menu(name='Lemon Chicken Rice', price=2.80, dining_area=diningarea_7)
menu_22 = model.Menu(name='Sambal Chicken Fried Rice', price=3.50, dining_area=diningarea_8)
menu_23 = model.Menu(name='Salted Fish Fried Rice', price=3.50, dining_area=diningarea_8)
menu_24 = model.Menu(name='Fried Rice with Prawn', price=3.50, dining_area=diningarea_8)
menu_25 = model.Menu(name='BBQ Chicken', price=3.80, dining_area=diningarea_9)
menu_26 = model.Menu(name='Fish Fillet', price=3.80, dining_area=diningarea_9)
menu_27 = model.Menu(name='Combo Meal (Chicken + Fish)', price=5.00, dining_area=diningarea_9)
menu_28 = model.Menu(name='Mixed Pork Soup', price=3.80, dining_area=diningarea_10)
menu_29 = model.Menu(name="Pig's Liver Soup'", price=3.80, dining_area=diningarea_10)
menu_30 = model.Menu(name='Lean Meat Soup', price=3.80, dining_area=diningarea_10)
menu_1.save()
menu_2.save()
menu_3.save()
menu_4.save()
menu_5.save()
menu_6.save()
menu_7.save()
menu_8.save()
menu_9.save()
menu_10.save()
menu_11.save()
menu_12.save()
menu_13.save()
menu_14.save()
menu_15.save()
menu_16.save()
menu_17.save()
menu_18.save()
menu_19.save()
menu_20.save()
menu_21.save()
menu_22.save()
menu_23.save()
menu_24.save()
menu_25.save()
menu_26.save()
menu_27.save()
menu_28.save()
menu_29.save()
menu_30.save()

# Tag
tag1 = model.Tag(name='North Spine Food Court', dining_area=diningarea_1)
tag2 = model.Tag(name='Hand-made Noodles', dining_area=diningarea_1)
tag3 = model.Tag(name='North Spine Food Court', dining_area=diningarea_2)
tag4 = model.Tag(name='Chicken Rice', dining_area=diningarea_2)
tag5 = model.Tag(name='North Spine Food Court', dining_area=diningarea_3)
tag6 = model.Tag(name='Mini Wok', dining_area=diningarea_3)
tag7 = model.Tag(name='North Spine Food Court', dining_area=diningarea_4)
tag8 = model.Tag(name='Soup Delight', dining_area=diningarea_4)
tag9 = model.Tag(name='North Spine Food Court', dining_area=diningarea_5)
tag10 = model.Tag(name='Western Food', dining_area=diningarea_5)
tag11 = model.Tag(name='North Spine Plaza', dining_area=diningarea_6)
tag12 = model.Tag(name='Hand-made Noodles', dining_area=diningarea_6)
tag13 = model.Tag(name='North Spine Plaza', dining_area=diningarea_7)
tag14 = model.Tag(name='Chicken Rice', dining_area=diningarea_7)
tag15 = model.Tag(name='North Spine Plaza', dining_area=diningarea_8)
tag16 = model.Tag(name='Mini Wok', dining_area=diningarea_8)
tag17 = model.Tag(name='North Spine Plaza', dining_area=diningarea_9)
tag18 = model.Tag(name='Soup Delight', dining_area=diningarea_9)
tag19 = model.Tag(name='North Spine Plaza', dining_area=diningarea_10)
tag20 = model.Tag(name='Western Food', dining_area=diningarea_10)
tag1.save()
tag2.save()
tag3.save()
tag4.save()
tag5.save()
tag6.save()
tag7.save()
tag8.save()
tag9.save()
tag10.save()
tag11.save()
tag12.save()
tag13.save()
tag14.save()
tag15.save()
tag16.save()
tag17.save()
tag18.save()
tag19.save()
tag20.save()

# Review
review1 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_1)
review2 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_1)
review3 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_1)
review4 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_1)
review5 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_1)
review6 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_1)
review7 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_1)
review8 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_1)
review9 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_1)
review10 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_1)
review11 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_2)
review12 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_2)
review13 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_2)
review14 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_2)
review15 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_2)
review16 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_2)
review17 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_2)
review18 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_2)
review19 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_2)
review20 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_2)
review21 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_3)
review22 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_3)
review23 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_3)
review24 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_3)
review25 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_3)
review26 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_3)
review27 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_3)
review28 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_3)
review29 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_3)
review30 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_3)
review31 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_4)
review32 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_4)
review33 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_4)
review34 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_4)
review35 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_4)
review36 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_4)
review37 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_4)
review38 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_4)
review39 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_4)
review40 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_4)
review41 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_5)
review42 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_5)
review43 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_5)
review44 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_5)
review45 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_5)
review46 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_5)
review47 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_5)
review48 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_5)
review49 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_5)
review50 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_5)
review51 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_6)
review52 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_6)
review53 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_6)
review54 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_6)
review55 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_6)
review56 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_6)
review57 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_6)
review58 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_6)
review59 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_6)
review60 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_6)
review61 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_7)
review62 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_7)
review63 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_7)
review64 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_7)
review65 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_7)
review66 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_7)
review67 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_7)
review68 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_7)
review69 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_7)
review70 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_7)
review71 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_8)
review72 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_8)
review73 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_8)
review74 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_8)
review75 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_8)
review76 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_8)
review77 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_8)
review78 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_8)
review79 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_8)
review80 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_8)
review81 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_9)
review82 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_9)
review83 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_9)
review84 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_9)
review85 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_9)
review86 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_9)
review87 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_9)
review88 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_9)
review89 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_9)
review90 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_9)
review91 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=1, dining_area=diningarea_10)
review92 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=2, dining_area=diningarea_10)
review93 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=3, dining_area=diningarea_10)
review94 = model.Review(reviewer="Leon", comment="It is average", date=datetime.datetime.now(), score=4, dining_area=diningarea_10)
review95 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=5, dining_area=diningarea_10)
review96 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=1, dining_area=diningarea_10)
review97 = model.Review(reviewer="Leon", comment="It is good", date=datetime.datetime.now(), score=2, dining_area=diningarea_10)
review98 = model.Review(reviewer="Leon", comment="It is bad", date=datetime.datetime.now(), score=3, dining_area=diningarea_10)
review99 = model.Review(reviewer="Leon", comment="It is ok", date=datetime.datetime.now(), score=4, dining_area=diningarea_10)
review100 = model.Review(reviewer="Leon", comment="It is awful", date=datetime.datetime.now(), score=1, dining_area=diningarea_10)
review1.save()
review2.save()
review3.save()
review4.save()
review5.save()
review6.save()
review7.save()
review8.save()
review9.save()
review10.save()
review11.save()
review12.save()
review13.save()
review14.save()
review15.save()
review16.save()
review17.save()
review18.save()
review19.save()
review20.save()
review21.save()
review22.save()
review23.save()
review24.save()
review25.save()
review26.save()
review27.save()
review28.save()
review29.save()
review30.save()
review31.save()
review32.save()
review33.save()
review34.save()
review35.save()
review36.save()
review37.save()
review38.save()
review39.save()
review40.save()
review41.save()
review42.save()
review43.save()
review44.save()
review45.save()
review46.save()
review47.save()
review48.save()
review49.save()
review50.save()
review51.save()
review52.save()
review53.save()
review54.save()
review55.save()
review56.save()
review57.save()
review58.save()
review59.save()
review60.save()
review61.save()
review62.save()
review63.save()
review64.save()
review65.save()
review66.save()
review67.save()
review68.save()
review69.save()
review70.save()
review71.save()
review72.save()
review73.save()
review74.save()
review75.save()
review76.save()
review77.save()
review78.save()
review79.save()
review80.save()
review81.save()
review82.save()
review83.save()
review84.save()
review85.save()
review86.save()
review87.save()
review88.save()
review89.save()
review90.save()
review91.save()
review92.save()
review93.save()
review94.save()
review95.save()
review96.save()
review97.save()
review98.save()
review99.save()
review100.save()