# Generated by Django 2.1.4 on 2019-05-17 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addr', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('operating_hour', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('dining_type', models.CharField(max_length=20)),
                ('imgurl', models.TextField()),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningAreaAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('dining_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DiningArea')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningAreaCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Cuisine')),
                ('dining_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DiningArea')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningSubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DiningCluster')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DishRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('dining_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DiningArea')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('dining_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DiningArea')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dining_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DiningArea')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='dishrecommendation',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Menu'),
        ),
        migrations.AddField(
            model_name='dishrecommendation',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Review'),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='sub_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DiningSubArea'),
        ),
    ]
